Adding saveEntitiesWithOptions to HKDatasource to allow passing forceAdd query parameter when saving entities
ibm-hyperknowledge/hklib pull request #89
Opened 2023-07-26 22:35 UTC by eltonfss

2023-07-26 23:00 UTC, raphaelgoms commented on src/datasource/hkdatasource.js
> +    this,this._saveEntities(entities, url, callback);
Two this here.

2023-07-27 13:02 UTC, raphael-melo requested changes
https://github.com/ibm-hyperknowledge/hklib/pull/89/files#r1275561391

2023-07-27 14:38 UTC, eltonfss commented on src/datasource/hkdatasource.js
> +    this,this._saveEntities(entities, url, callback);
Thank you!

2023-07-27 14:51 UTC, raphael-melo approved these changes

2023-07-27 15:35 UTC, marcelomachado approved these changes

2023-07-27 15:37 UTC, merged